clean:
	rm -rf *.md *.html *.pdf cache/ figure/

%.html: %.Rmd
	./make_slides $(basename $(@))

all: clean 0 1 2 3 4 5 6 7 8 9 10 11 12



1: 1_nimble_background.html
9: 9_operating_model.html
6: 6_user_dist.html
0: overview.html
10: 10_model_structure.html
2: 2_bugs_language.html
4: 4_customizing_mcmc.html
7: 7_highlights.html
11: 11_user_sampler.html
12: 12_wrapup.html
3: 3_basic_use.html
5: 5_nimble_bugs.html
8: 8_basic_nimbleFunction.html
